# Интерактивный учебный комплекс по машинному обучению для анализа физических систем 



В последние годы все больше применений в современной науке находят методы, основанные на машинном 
обучении и науке о данных. Высокая эффективность таких методов для решения дифференциальных 
уравнений и задач классификации делает их перспективными для использовании в области физики.
Таким образом, возникает необходимость оперативной адаптации множества современных научных и 
учебных публикаций в области машинного обучения к программе и уровню знаний студентов физических
специальностей. Кроме того, в связи со спецификой предмета возникает необходимость в интерактивных 
практикумах, включающих в себя исполняемые коды для демонстрации основных концепций. 
В связи с этим, задача по отбору, анализу и подготовке учебных материалов в области машинного обучения для
физиков требует уровня подготовки, соответствующего магистранту физического факультета.




# Что такое машинное обучение?

***Введение в науку о данных и машинное обучение***

[Презентация](https://docs.google.com/presentation/d/1gI9u4XRER896o7MD280_rzwDBM6KWqyZGP_Nd0BCLks/edit#slide=id.g183f84a2175_0_24)

[Лекция](https://docs.google.com/document/d/1zVM2wSK54OMsoYJgZheGyhxYF3a4ZT6XnT5zGEHj9jM/edit)

[Применение машинного обучения в различных сферах](https://docs.google.com/presentation/d/1o1UkxS9FNtwr7CUGMHz5w2FOcim767vX/edit#slide=id.g207dc08dad8_0_222)

# Необходимая подготовка


Для эффективного изучения необходимо выполнить следующие пункты:


1.  [Установить интерпретатор Python](https://www.python.org/downloads/)

2.  [Установить PyCharm](https://www.jetbrains.com/ru-ru/pycharm/) (для студентов доступны бесплатные версии Professional Edition) или другую IDE

3.  [Установка дистрибутива Anaconda (по желанию)](https://www.anaconda.com/)

4.  Также можно использовать [Google Colaboratory](https://colab.research.google.com/) или [Jupiter Notebook](https://jupyter.org/try) в этом случае вам не придется проделывать шаги 1-3 :)

Для запуска ячеек с кодом используйте Shift + Enter или play

# NumPy


NumPy

Библиотека NumPy (сокращение от Numerical Python — «числовой Python») обе- спечивает эффективный интерфейс для хранения и работы с плотными буферами данных. Массивы библиотеки NumPy похожи на встроенный тип данных языка Python list, но обеспечивают гораздо более эффективное хранение и операции с данными при росте размера массивов. Массивы библиотеки NumPy формируют ядро практически всей экосистемы утилит для исследования данных Python. Время, проведенное за изучением способов эффективного использования пакета
NumPy, не будет потрачено впустую вне зависимости от интересующего вас аспек- та науки о данных.

Numpy предоставляет  𝑛 -мерные однородные массивы (все элементы одного типа); в них нельзя вставить или удалить элемент в произвольном месте. В numpy реализовано много операций над массивами в целом. Если задачу можно решить, произведя некоторую последовательность операций над массивами, то это будет столь же эффективно, как в C или matlab — львиная доля времени тратится в библиотечных функциях, написанных на C.

Если сравнивать NumPy с другим ПО для математических вычислений, например MATLAB, то в своей области — линейная алгебра, операции над векторами (массивами) и матрицами — «герой» нашей статьи покрывает абсолютное большинство нужд, обеспечиваемых последним, а в некоторых областях даже превосходит его.

Ключевые различия NumPy и MATLAB



1.   В MATLAB базовый тип даже для скалярных (в частности, числовых) данных — многомерный массив.
Массивы в MATLAB хранятся как двумерные массивы из чисел с плавающей точкой с двойной точностью, кроме случаев, когда вы сами указываете количество измерений и тип. Операции над двумерными экземплярами этих массивов основываются на матричных операциях линейной алгебры.

*   MATLAB начинает нумерацию (индексацию) начиная с 1; a(1) — это первый элемент.
*   Язык сценариев (скриптовый язык) MATLAB был создан для поддержки привычной нотации линейной алгебры, поэтому синтаксис для некоторых операций с массивами более компактный, чем в NumPy.

*   Нарезание (slicing) массивов в MATLAB использует семантику передачи по ссылке, с «ленивым» (отложенным) копированием во время записи, чтобы избежать создания копий данных до момента когда они необходимы. Операции нарезания копируют части массива.




2.   В NumPy, базовый тип — это многомерный массив. Переменные типа «массив» в NumPy обычно хранятся в n-мерных массивах с «минимальным» (наименее затратном в смысле занимаемой памяти) типом, необходимым для хранения объектов в последовательности, кроме случаев, когда вы задаете количество измерений и тип.
NumPy производит поэлементные операции, поэтому перемножение двумерных массивов операцией «*» — это не перемножение матриц, это именно умножение элемента-на-элемент. Оператор «@», доступный начиная с версии Python 3.5, может использоваться для привычного перемножения матриц.


*   NumPy, так же как Python и абсолютное большинство современных языков программирования, начинает индексацию с 0; первым элементом будет a[0].
*   NumPy основан на Python, языке программирования общего назначения. Преимущество NumPy — в полноценном и неограниченном доступе к питоновским библиотекам, включая SciPy, Matplotlib, Pandas, OpenCV, и так далее. Вдобавок, Python часто встроен (embedded) в качестве скриптового языка в другое программное и даже аппаратное (например, NVIDIA CUDA) обеспечение, тем самым позволяя использовать NumPy в этих платформах.


*   Операция нарезания в NumPy использует передачу по ссылке, что позволяет избежать копирования аргументов. Результаты операций нарезания на самом деле представления (Views) массивов, а не копии массивов.


































# Установка NumPy
**Ubuntu Linux**
1.   sudo apt update -y
2.   sudo apt upgrade -y
3.   sudo apt install python3-tk python3-pip -y
4.   sudo pip install numpy -y

**Anaconda**
*   conda install -c anaconda numpy

** Через терминал **
*   pip install numpy

Подробнее об установке:

*   [NumPy Pypi](https://pypi.org/project/numpy/)
*   [Официальная документация](https://numpy.org/)




# NumPy использование

**Чтобы проверить, что numpy установлен Вы можете импортировать его и вызвать дандер метод __version__ (используйте 2 нижних подчеркивания)**

In [ ]:
import numpy
print(numpy.__version__)

1.21.6


**Импорт NumPy как np для удобного использования и создание массивов**


In [ ]:
import numpy as np

python_list = [1, 2, 3, 4, 5, 6]
numpy_array = np.array(python_list)

message = f"Список {python_list} имеет тип данных - {type(python_list)}, а созданный \n на его основе массив numpy: {numpy_array} имеет тип {type(numpy_array)}" 

print(message)


Список [1, 2, 3, 4, 5, 6] имеет тип данных - <class 'list'>, а созданный 
 на его основе массив numpy: [1 2 3 4 5 6] имеет тип <class 'numpy.ndarray'>


**Создание массива с помощью arange**

np.arange(start, stop, step)

**Примечание**
Обратите внимание, что мы создаем массив похожим способом как создавали бы генератор с помощью range() в чистом Python. Также, стоит учитывать что значение ***stop*** не включается


In [ ]:
import numpy as np

flat_array = np.arange(5)

test_arr = np.arange(1, 10)

param_arr = np.arange(1, 1000, 50)

print(f"flat_array \n{flat_array}\n test_arr: \n{test_arr}\n param_arr \n{param_arr}")


flat_array 
[0 1 2 3 4]
 test_arr: 
[1 2 3 4 5 6 7 8 9]
 param_arr 
[  1  51 101 151 201 251 301 351 401 451 501 551 601 651 701 751 801 851
 901 951]



**Преобразование матрицы 3x3 из list в numpy array**


In [ ]:
import numpy as np

test_matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]

numpy_matrix = np.array(test_matrix)
print(f"{test_matrix}={type(test_matrix)},\n{numpy_matrix}={type(numpy_matrix)}")

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]=<class 'list'>,
[[1 2 3]
 [4 5 6]
 [7 8 9]]=<class 'numpy.ndarray'>


**Создание массива, состоящего из нулей**

np.zeros(i,j) - где i - количество строк, j - количество столбцов (по умолчанию равно 0). Также в качестве необязательного аргумента можно указывать, 
dtype = int тогда все элементы массива будут принадлежать типу int

**Примечание**
Если нам необходимо создать нулевую матрицу с ненулевым j пару значений i,j следует передавать в функцию в виде кортежа с элементами i,j




In [ ]:
import numpy as np

flat_array = np.zeros(5, dtype= int)
zero_matrix = np.zeros((3,3), dtype = float)

print(f'{flat_array} - flat_array', "\n", f'\n zero_matrix: \n {zero_matrix}')

[0 0 0 0 0] - flat_array 
 
 zero_matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

flat_array = np.ones(5, dtype = float)
ones_matrix = np.ones((3,3), dtype= int)

print(f'{flat_array} - flat_array', "\n", f'\n ones_matrix: \n {ones_matrix}')


[1. 1. 1. 1. 1.] - flat_array 
 
 ones_matrix: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


**Создание линейного пространства определенной размерности**
В случае, когда нам нужно создать массив определенной размерности, значения которого входят в один диапазон хорошим решением станет использование функции ***linspace(start, stop, length)***, по умолчанию length = 50

In [ ]:
import numpy as np

fisrt_linsp = np.linspace(0,10,32)
second_linsp = np.linspace(0,10)

print(f'Линейное пространство с указанием количества элементов: \n {fisrt_linsp}')
print(f"Количество элементов в массиве = {len(fisrt_linsp)}")
print('------------------------------------------------')

print(f'Пространство без указания количества элементов {second_linsp}')
print(f'Количество элементов в массиве по умолчанию равно {len(second_linsp)}')





Линейное пространство с указанием количества элементов: 
 [ 0.          0.32258065  0.64516129  0.96774194  1.29032258  1.61290323
  1.93548387  2.25806452  2.58064516  2.90322581  3.22580645  3.5483871
  3.87096774  4.19354839  4.51612903  4.83870968  5.16129032  5.48387097
  5.80645161  6.12903226  6.4516129   6.77419355  7.09677419  7.41935484
  7.74193548  8.06451613  8.38709677  8.70967742  9.03225806  9.35483871
  9.67741935 10.        ]
Количество элементов в массиве = 32
------------------------------------------------
Пространство без указания количества элементов [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.938

**Создание единичной матрицы**
np.eye(N), где N - размерность 

In [ ]:
import numpy as np

matrix = np.eye(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Создание массива со случайными значениями**

np.random.rand(i, j), где i - строки, j - столбцы(если не передавать, по умолчанию используется 0)

In [ ]:
import numpy as np

arr = np.random.rand(3,4)
print(type(arr),'\n', arr)

flat_arr = np.random.rand(3)
print('--------------------------')
print(type(flat_arr), '\n', flat_arr)


<class 'numpy.ndarray'> 
 [[0.21590649 0.93797167 0.45809725 0.88096032]
 [0.94832773 0.38667628 0.54960955 0.59518285]
 [0.56064744 0.35696249 0.76171636 0.01055389]]
--------------------------
<class 'numpy.ndarray'> 
 [0.57394051 0.19586616 0.35857444]


**Создание массива со случайными целыми значениями**

np.random.randint(start, stop, size)

Параметр size можно представить в виде кортежа (i,j), где i,j строки и столбцы соответственно.


In [ ]:
import numpy as np

matrix = np.random.randint(0,101, (4,5))
print(matrix)


[[18 93 77 22 23]
 [94 11 28 74 88]
 [ 9 15 18 80 71]
 [88 11 17 46  7]]


**Аттрибуты массива Numpy**


In [ ]:
import numpy as np

matrix = np.random.randint(0,10, (3,3))




array([[0, 0, 6],
       [9, 1, 8],
       [9, 1, 2]])

# Изменение размера массива с помощью метода reshape

matrix.reshape(i, j)  
где matrix - объект исходного массива NumPy, а i, j размерность нового массива.


In [ ]:
import numpy as np

print('Массив размером 10x10 \n')
matrix = np.random.randint(0, 100,(10,10))
print(matrix)
print('________________________ \n')

print('Массив размером 25x4 \n')
arr = matrix.reshape(25,4)
print(arr)

print('________________________ \n')
print('Массив размером 4x25 \n')
arr = matrix.reshape(4,25)
print(arr)


Массив размером 10x10 

[[ 4 25 70 55 20 26 67 45 53 34]
 [59 74 47 59 40 97 32 48 66 56]
 [89 20  0 16 13 97 92 73  2 57]
 [37 59 18 22 73 80 93 32 54 16]
 [31 57 66 46 36 63 93 60 72 62]
 [27 55 47 48 89 20 28 54 15  2]
 [50 33 99  7 15 53 58 55 80 39]
 [81 14 38 76  8 94 83 79 80 47]
 [80  5 11 95 25 23 22 58 51  6]
 [49  8 57 23 72 66 37 51 24 70]]
________________________ 

Массив размером 25x4 

[[ 4 25 70 55]
 [20 26 67 45]
 [53 34 59 74]
 [47 59 40 97]
 [32 48 66 56]
 [89 20  0 16]
 [13 97 92 73]
 [ 2 57 37 59]
 [18 22 73 80]
 [93 32 54 16]
 [31 57 66 46]
 [36 63 93 60]
 [72 62 27 55]
 [47 48 89 20]
 [28 54 15  2]
 [50 33 99  7]
 [15 53 58 55]
 [80 39 81 14]
 [38 76  8 94]
 [83 79 80 47]
 [80  5 11 95]
 [25 23 22 58]
 [51  6 49  8]
 [57 23 72 66]
 [37 51 24 70]]
________________________ 

Массив размером 4x25 

[[ 4 25 70 55 20 26 67 45 53 34 59 74 47 59 40 97 32 48 66 56 89 20  0 16
  13]
 [97 92 73  2 57 37 59 18 22 73 80 93 32 54 16 31 57 66 46 36 63 93 60 72
  62]
 [27 55 4

# Создание массива случайных элементов

np.emty((rows, columns)), 
columns = 0 по умолчанию

In [ ]:
import numpy as np

flat_arr = np.empty(4)
print(flat_arr)

print('\n массив 4x4 \n')
arr = np.empty((4,4))
print(arr)

[0.75 0.75 0.  ]

 массив 4x4 

[[1.69653763e-316 3.80430547e-322 0.00000000e+000 0.00000000e+000]
 [2.01589600e-312 1.50008929e+248 4.31174539e-096 9.80058441e+252]
 [1.23971686e+224 2.59032240e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 2.66023306e-312 0.00000000e+000]]


# Аттрибуты массива NumPy


In [ ]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ])


rang = arr.ndim
size = arr.size
shape = arr.shape
data_type = arr.dtype
bytes_number = arr.itemsize 
s = arr.sum()
min_elem = arr.min()
max_elem = arr.max()


info = {
  'Ранг матрицы': arr.ndim,
  'Количество элементов матрицы': size,
  'Размерность матрицы': shape,
  'Тип данных для элементов матрицы': data_type,
  'Размер каждого элемента в массиве в байтах': bytes_number,
  'Сумма элементов': s,
  'Минимльный элемент': min_elem,
  'Максимальный элемент': max_elem
}

print(info)


# Тригонометрические функции  с массивами NumPy



In [ ]:
import numpy as np


matrix = np.array([
    [1,0,1],
    [0,1,-1]
])

trigonometry_dictionary = {
    "sin_matrix": np.sin(matrix),
    "arcsin_matrix": np.arcsin(matrix),
    "cos_matrix": np.cos(matrix),
    "arccos_matrix": np.arccos(matrix),
    "tan_matrix": np.tan(matrix),
    "arctan_matrix": np.arctan(matrix)
}


for key, value in trigonometry_dictionary.items():
  print(key)
  print(value)
  print('--------------------------------------')







sin_matrix
[[ 0.84147098  0.          0.84147098]
 [ 0.          0.84147098 -0.84147098]]
--------------------------------------
arcsin_matrix
[[ 1.57079633  0.          1.57079633]
 [ 0.          1.57079633 -1.57079633]]
--------------------------------------
cos_matrix
[[0.54030231 1.         0.54030231]
 [1.         0.54030231 0.54030231]]
--------------------------------------
arccos_matrix
[[0.         1.57079633 0.        ]
 [1.57079633 0.         3.14159265]]
--------------------------------------
tan_matrix
[[ 1.55740772  0.          1.55740772]
 [ 0.          1.55740772 -1.55740772]]
--------------------------------------
arctan_matrix
[[ 0.78539816  0.          0.78539816]
 [ 0.          0.78539816 -0.78539816]]
--------------------------------------


# **Гиперболические функции**

In [ ]:
import numpy as np


matrix = np.array([
    [0.5,0.9,0.7],
    [-0.8,0.3,-0.6]
])

hypertrig_dict = {
    "sinh(matrix)": np.sinh(matrix),
    "cosh(matrix)": np.cosh(matrix),
    "tanh(matrix)": np.tanh(matrix),
    "arcsinh(matrix)":np.arcsinh(matrix),
    "arccosh(matrix)":np.arccosh(np.array([1,1,1])),
    "arctanh(matrix)":np.arctanh(matrix),
}

for key, value in hypertrig_dict.items():
  print(key)
  print(value)
  print('--------------------------------------')

sinh(matrix)
[[ 0.52109531  1.02651673  0.7585837 ]
 [-0.88810598  0.30452029 -0.63665358]]
--------------------------------------
cosh(matrix)
[[1.12762597 1.43308639 1.25516901]
 [1.33743495 1.04533851 1.18546522]]
--------------------------------------
tanh(matrix)
[[ 0.46211716  0.71629787  0.60436778]
 [-0.66403677  0.29131261 -0.53704957]]
--------------------------------------
arcsinh(matrix)
[[ 0.48121183  0.80886694  0.65266657]
 [-0.73266826  0.29567305 -0.5688249 ]]
--------------------------------------
arccosh(matrix)
[0. 0. 0.]
--------------------------------------
arctanh(matrix)
[[ 0.54930614  1.47221949  0.86730053]
 [-1.09861229  0.3095196  -0.69314718]]
--------------------------------------


# NumPy и линейная алгебра

# Создание матрицы и вычисление определителя

В NumPy есть класс linalg, поддерживающий операции линейной алгебры


In [ ]:
import numpy as np

matrix = np.random.randint(0,10, (3,3))

determ = np.linalg.det(matrix)

print("Исходная матрица")
print(matrix)
print("Определитель равен", determ)




Исходная матрица
[[0 1 0]
 [4 1 9]
 [2 2 0]]
Определитель равен 17.999999999999996


#***Базовые операции с массивом NumPy***
Возведение в степень, транспонирование, сложение, вычитание, умножение матриц

# ***Умножение матриц***

In [ ]:
import numpy as np

A = np.random.randint(0,10, (3,3))

B = np.random.randint(0,10, (3,3))

C = np.dot(A,B)
print("Произведение матрицы")
print(A)
print("на матрицу")
print(B)
print("Результат: ")
print(C)


print("Теперь поменяем слагаемые местами и умножим вторую матрицу на первую")

print(np.dot(B,A))

Произведение матрицы
[[5 3 4]
 [4 9 8]
 [9 4 9]]
на матрицу
[[8 8 0]
 [0 4 2]
 [8 8 9]]
Результат: 
[[ 72  84  42]
 [ 96 132  90]
 [144 160  89]]
Теперь поменяем слагаемые местами и умножим вторую матрицу на первую
[[ 72  96  96]
 [ 34  44  50]
 [153 132 177]]


# ***Транспонирование матриц***


In [ ]:
import numpy as np

A = np.random.randint(0,10, (3,3))

print("Исходная матрица")
print(A)
print("Транспонированная матрица")
print(A.transpose())

Исходная матрица
[[8 9 1]
 [7 2 1]
 [1 0 5]]
Транспонированная матрица
[[8 7 1]
 [9 2 0]
 [1 1 5]]


# ***Возведение в степень***

np.linalg.matrix_power(A, n) - где A - это исходная матрица, а n - показатель степени

In [ ]:
import numpy as np

n = int(input("Введите n: "))

A = np.random.randint(0,10, (3,3))

B = np.linalg.matrix_power(A, n)

print("Исходная матрица")
print(A)

print(f"Матрица возведенная в степень {n}")
print(B)


Введите n: 3
Исходная матрица
[[4 0 2]
 [8 1 9]
 [4 8 7]]
Матрица возведенная в степень 3
[[ 312  192  346]
 [1240  777 1425]
 [1460 1096 1695]]


# ***Вычисление обратной матрицы***


Решим задачу определения обратной матрицы на Python. 
Для получения обратной
матрицы будем использовать функцию inv():

In [ ]:
import numpy as np

matrix = np.random.randint(0,10, (3,3))

inv_matrix = np.linalg.inv(matrix)

print(inv_matrix)



[[ 0.07042254  0.11971831 -0.21830986]
 [ 0.28169014 -0.02112676 -0.37323944]
 [-0.23943662 -0.00704225  0.54225352]]


# ***QR-разложение матрицы***

QR разложение позволяет представить матрицу A в виде произведения QR, где Q - это ортогональная (унитарная) матрица, а R - это верхнетреугольная матрица.

In [ ]:
import numpy as np

A = np.random.randint(0,10, (3,3))

Q,R = np.linalg.qr(matrix)
print('Матрица А')
print(A)
print('_____________')
print('Матрица Q')
print(Q)
print('_____________')
print('Матрица R')
print(R)

Матрица А
[[4 7 6]
 [0 5 5]
 [7 6 2]]
_____________
Матрица Q
[[-0.56225353  0.8229362   0.08152896]
 [-0.40160966 -0.18554265 -0.8968186 ]
 [-0.7228974  -0.53698224  0.43482114]]
_____________
Матрица R
[[-12.4498996   -6.1044669  -12.4498996 ]
 [  0.          -2.9555852    1.69171236]
 [  0.           0.          -4.81020886]]


# ***Сингулярное (SVD) разложение матрицы***

Функция np.linalg.svd(matrix) возвращает кортеж из трех значений, обозначим их как U, S, Vh.
Так как SVD позволяет представить матрицу A размером (m, n) в виде произведения 
A=UΣV∗


In [ ]:
import numpy as np

A = np.random.randint(0,10, (3,3))

U, S, Vh = np.linalg.svd(A)

print("Матрица А")

print("Результат SVD:")

print("Матрица U")
print(U)

print("Матрица S")
print(S)

print("Матрица Vh")
print(Vh)




Матрица А
Результат SVD:
Матрица U
[[-0.45276325 -0.76370376 -0.46017605]
 [-0.87840106  0.29347207  0.3772078 ]
 [-0.1530262   0.57500496 -0.80371157]]
Матрица S
[14.27187499  6.02762126  2.23189747]
Матрица Vh
[[-0.28907968 -0.80772257 -0.51382603]
 [ 0.57633152 -0.57541463  0.58029301]
 [-0.76437878 -0.12838322  0.63185665]]


# ***Среднее значение массива Numpy***

Для вычисления среднего значения массива Numpy можно использовать функцию average() или mean().

Рассмотрим пример ниже.

In [ ]:
import numpy as np

A = np.random.randint(0,10, (3,3))

avg = np.average(A)
m_avg = np.mean(A)

print("Исходная матрица")
print(A)
print("---------------")
print("Среднее значение:", avg)
print("Среднее значение через функцию mean:", m_avg)

Исходная матрица
[[2 0 1]
 [5 1 8]
 [7 8 7]]
---------------
Среднее значение: 4.333333333333333
Среднее значение через функцию mean: 4.333333333333333


# ***Стандартное отклонение значений элементов массива расположенных вдоль указанной оси.***


Функция std() вычисляет среднеквадратичное (стандартное) отклонение значений элементов массива.



In [ ]:
import numpy as np

A = np.random.randint(0,10, (3,3))

st_d = np.std(A)

print("Исходная матрица")
print(A)
print("---------------")
print("Среднеквадратичное отклонение значений элементов массива")
print(st_d)



Исходная матрица
[[4 0 5]
 [5 7 4]
 [4 9 2]]
---------------
Среднеквадратичное отклонение значений элементов массива
2.454524670486058


# ***Дисперсия значений элементов массива***

In [ ]:
import numpy as np

A = np.random.randint(0,10, (3,3))

v = np.var(A)

print("Исходная матрица")
print(A)
print("---------------")
print("Дисперсия значений элементов массива")
print(v)


Исходная матрица
[[8 7 2]
 [3 5 1]
 [3 7 6]]
---------------
Дисперсия значений элементов массива
5.555555555555555


linalg.solve(a, b) - решает систему :\линейных уравнений Ax = b.


# ***Произведение Кронекера***

In [ ]:
import numpy as np

A = np.random.randint(0,10, (1,2))
B = np.random.randint(0,10, (1,2))

kr = np.kron(A,B)
print("Матрица А")
print(A)

print("__________")
print("Матрица B")
print(B)
print("__________")

print("Произведение Кронекера")
print(kr)
print("__________")

#Изменим размерности матриц

A = np.random.randint(0,10, (2,2))
B = np.random.randint(0,10, (3,2))

kr = np.kron(A,B)
print("Матрица А")
print(A)

print("__________")
print("Матрица B")
print(B)
print("__________")

print("Произведение Кронекера")
print(kr)
print("__________")


#Изменим размерности матриц

A = np.random.randint(0,10, (3,3))
B = np.random.randint(0,10, (3,3))

kr = np.kron(A,B)
print("Матрица А")
print(A)

print("__________")
print("Матрица B")
print(B)
print("__________")

print("Произведение Кронекера")
print(kr)
print("__________")



Матрица А
[[7 4]]
__________
Матрица B
[[5 9]]
__________
Произведение Кронекера
[[35 63 20 36]]
__________
Матрица А
[[9 7]
 [7 4]]
__________
Матрица B
[[5 5]
 [5 7]
 [3 6]]
__________
Произведение Кронекера
[[45 45 35 35]
 [45 63 35 49]
 [27 54 21 42]
 [35 35 20 20]
 [35 49 20 28]
 [21 42 12 24]]
__________
Матрица А
[[2 4 4]
 [9 9 6]
 [0 6 2]]
__________
Матрица B
[[0 4 5]
 [7 8 9]
 [0 0 7]]
__________
Произведение Кронекера
[[ 0  8 10  0 16 20  0 16 20]
 [14 16 18 28 32 36 28 32 36]
 [ 0  0 14  0  0 28  0  0 28]
 [ 0 36 45  0 36 45  0 24 30]
 [63 72 81 63 72 81 42 48 54]
 [ 0  0 63  0  0 63  0  0 42]
 [ 0  0  0  0 24 30  0  8 10]
 [ 0  0  0 42 48 54 14 16 18]
 [ 0  0  0  0  0 42  0  0 14]]
__________


# ***Работа с файлами***

In [ ]:
import numpy as np

test_matrix_a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]

test_matrix_b = [
    [4,7,3],
    [1,2,9],
    [2,8,5]
  ]

# Запись матриц в файл matrixes

A = np.array(test_matrix)
B = np.array(test_matrix)

np.save('matrixes', A, B)

print("В файл matrixes записаны матрицы:")
print("Матрица А:")
print(A)
print("Матрица B:")
print(B)


# Загрузка данных из файла

a = np.load('matrixes.npy')
b = np.load('matrixes.npy')
print("Из файла matrixes загружены следующие матрицы:")
print("Матрица А:")
print(a)
print("Матрица B:")
print(b)


В файл matrixes записаны матрицы:
Матрица А:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Матрица B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Из файла matrixes загружены следующие матрицы:
Матрица А:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Матрица B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# ***Ufunc Numpy***

Универсальная функция (или сокращенно ufunc) - это функция, которая работает с массивами ndarrays поэлементно, поддерживая широковещательную передачу массивов, приведение типов и ряд других стандартных функций. 
То есть ufunc - это “векторизованная” оболочка для функции, которая принимает фиксированное количество определенных входных данных и выдает фиксированное количество определенных выходных данных. Для получения подробной информации об универсальных функциях см. 
 [Основы универсальных функций (ufunc)](https://numpy.org/doc/stable/user/basics.ufuncs.html#ufuncs-basics)

Все ufuncs имеют четыре метода. Их можно найти на сайте [Methods](https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs-methods). Однако эти методы имеют смысл только для скалярных ufuncs, которые принимают два входных аргумента и возвращают один выходной аргумент. Попытка вызвать эти методы в других ufuncs вызовет ValueError.

# ***Зачем использовать Ufuncs?***
ufuncs используются для реализации векторизации в NumPy, что намного быстрее, чем перебор элементов.

Они также предоставляют широковещательную передачу и дополнительные методы, такие как уменьшение, накопление и т.д., Которые очень полезны для вычислений.

ufuncs также принимают дополнительные аргументы, такие как:

where - boolean array or condition defining where the operations should take place.
Данный параметр принимает True (по умолчанию), False или массив логических значений в случае если универсальная функция возвращает несколько результирующих массивов. Значение True указывает на вычисление универсальной функции с сохранением результата в указанный в параметре out массив. В случае указания False, будут возвращены значения массива, который указан в out.

Параметр where может оказаться полезен, в ситуациях когда обработку данных и сохранение вычислений необходимо выполнять в зависимости от некоторого условия. Например, необходимость обработки данных зависит от некоторого параметра c, который должен находиться в пределах некоторого интервала.

dtype -  defining the return type of elements. Позволяет переопределить тип данных выходного массива.





out - output array where the return value should be copied. Определяет место в которое будет сохранен результат функции. Если параметр не указан или указано None (по умолчанию), то будет возвращен автоматически созданный массив. Если в качестве параметра указан массив NumPy, то он должен иметь форму совместимую с формой входного массива. Если универсальная функция создает несколько выходных массивов, то для каждого из них можно указать место сохранения с помощью кортежа из массивов NumPy или None.

Данный параметр очень полезен при больших вычислениях, так как позволяет избежать создания временного массива, записывая результат, непосредственно в то место памяти в которое необходимо.

# ***Что такое векторизация?***
Преобразование итеративных инструкций в векторную операцию называется векторизацией.

Это быстрее, поскольку современные процессоры оптимизированы для таких операций.

# ***Сложение элементов***

In [ ]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


# ***Сложение элементов с помощью ufunc***



In [ ]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)


[ 5  7  9 11]


# ***Создание собственной ufunc***

Чтобы создать свой собственный ufunc, вы должны определить функцию, как вы делаете с обычными функциями в Python, затем вы добавляете ее в свою библиотеку NumPy ufunc с помощью метода frompyfunc().


# ***Метод frompyfunc() принимает следующие аргументы:***

function - название функции.

inputs - количество входных аргументов (массивов).

outputs - количество выходных массивов.

In [ ]:
import numpy as np

def custom_multiply(x, y):
  return x*y

custom_ufunc = np.frompyfunc(custom_multiply, 2, 1)

print(f"Результатом работы функции типа: {type(custom_ufunc)}, является {custom_ufunc([1, 2, 3, 4], [5, 6, 7, 8])}")


Результатом работы функции типа: <class 'numpy.ufunc'>, является [5 12 21 32]


# ***Subtraction***

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

result = np.subtract(arr1, arr2)

print(result)

[-10  -1   8  17  26  35]


# ***Multiplication***


In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

result = np.multiply(arr1, arr2)

print(result)

[ 200  420  660  920 1200 1500]


# ***Division***

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

result = np.divide(arr1, arr2)

print(result)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


# ***Power***

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

res = np.power(arr1, arr2)

print(res)

[         1000       3200000     729000000 6553600000000          2500
             0]


# ***Remainder***

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


# ***Quotient and Mod***

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

res = np.divmod(arr1, arr2)

print(res)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))



# ***Absolute Values***

In [ ]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

res = np.absolute(arr)

print(res)

[1 2 1 2 3 4]


# ***Округление десятичных дробей***
В NumPy существует в основном пять способов округления десятичных дробей:

*   truncation
*   fix
*   rounding
*  floor
*   ceil

# ***Truncation***

In [ ]:
import numpy as np

arr = np.trunc([-7.12592, 4.12592])

print(arr)

[-7.  4.]


In [ ]:
import numpy as np

arr = np.fix([-7.12592, 4.12592])

print(arr)

[-7.  4.]


# ***Rounding***

In [ ]:
import numpy as np

arr = np.around(4.12592, 3)

print(arr)

4.126


# ***Floor***



In [ ]:
import numpy as np

arr = np.floor([4.12592, -7.12592])

print(arr)

[-4.  3.]


# ***Ceil***

In [ ]:
import numpy as np

arr = np.ceil([4.12592, -7.12592])

print(arr)

[ 5. -7.]


# ***Логарифмирование с NumPy***

***Логарифм с основанием 2***

In [ ]:
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


***Логарифм с основанием 10*** 

In [ ]:
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


***Натуральный логарифм*** 

In [ ]:
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


# ***Логарифм с любым основанием***

In [ ]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(81, 3))

4.0


# ***Произведение***

Чтобы найти произведение элементов в массиве, используйте функцию prod().


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

res = np.prod([arr1, arr2])

print(res)

40320


# ***NumPy Differences***

In [ ]:
import numpy as np

arr = np.array([10, 15, 25, 5])

res = np.diff(arr)

print(res)

# [5 10 -20] потому что 15-10=5, 25-15=10, и 5-25=-20

[  5  10 -20]


In [ ]:
import numpy as np

arr = np.array([10, 15, 25, 5])

res = np.diff(arr, n=2)

print(res)
# [5 -30] потому что: 15-10=5, 25-15=10, и 5-25=-20 и 10-5=5 и -20-10=-30

[  5 -30]


# ***NumPy LCM Lowest Common Multiple***

Наименьшее общее кратное

In [ ]:
import numpy as np

num1 = 10
num2 = 20

x = np.lcm(num1, num2)

print(x)

20


In [ ]:
import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)
# Возвращает: 18, потому что это наименьшее общее кратное из всех трех чисел (3*6=18, 6*3=18 и 9*2=18).

18


# ***NumPy GCD Greatest Common Denominator***

Наибольший общий делитель

In [ ]:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [ ]:
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

res = np.gcd.reduce(arr)

print(res)

4



# ***NumPy Set Operations***


# **Что такое множество?**
Множество в математике - это набор уникальных элементов.

Наборы используются для операций, включающих частые операции пересечения, объединения и разности.

# ***Создание множества***

In [ ]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


***Чтобы найти уникальные значения двух массивов, используйте метод union()***

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

res = np.union1d(arr1, arr2)

print(res)

[1 2 3 4 5 6]


# ***Пересечение двух множеств***


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

res = np.intersect1d(arr1, arr2, assume_unique=True)

print(res)

[3 4]


# ***Finding Difference***

Чтобы найти только значения в первом множестве, которых нет во втором множестве, используйте метод setdiff1d().

In [ ]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

res = np.setdiff1d(set1, set2, assume_unique=True)

print(res)

[1 2]


# ***Symmetric Difference***

In [ ]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

res = np.setxor1d(set1, set2, assume_unique=True)

print(res)

[1 2 5 6]


# ***Тригонометрические функции NumPy***

In [ ]:
import numpy as np

x = np.sin(np.pi/2)
y = np.cos(np.pi/2)
z = np.tan(np.pi/2)

x,y,z

(1.0, 6.123233995736766e-17, 1.633123935319537e+16)

In [ ]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


# ***Перевод градусов в радианы NumPy***


In [ ]:
import numpy as np
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


# ***Перевод радиан в градусы NumPy***

In [ ]:
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


# ***Поиск углов***

In [ ]:
import numpy as np

x = np.arcsin(1.0)
y = np.arccos(1.0)
z = np.arctan(1.0)

x,y,z

(1.5707963267948966, 0.0, 0.7853981633974483)

# ***Поиск углов для каждого элемента массива***

In [ ]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


# ***Вычисление гипотенузы***

In [ ]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0



# ***Гиперболические функции***

In [ ]:
import numpy as np

x = np.sinh(np.pi/2)
y = np.cosh(np.pi/2)
z = np.tanh(np.pi/2)

x,y,z

(2.3012989023072947, 2.5091784786580567, 0.9171523356672744)

# ***Выисление значений гиперболических функций для каждого элемента массива***

In [ ]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sinh(arr)
y = np.cosh(arr)
z = np.tanh(arr)

x,y,z

(array([2.3012989 , 1.24936705, 0.86867096, 0.670484  ]),
 array([2.50917848, 1.60028686, 1.32460909, 1.20397209]),
 array([0.91715234, 0.78071444, 0.6557942 , 0.55689331]))

# ***Поиск углов***

In [ ]:
import numpy as np

x = np.arcsinh(1.0)
y = np.arccosh(1.0)
z = np.arctanh(0.7)

x,y,z

(0.881373587019543, 0.0, 0.8673005276940531)

# ***Определение угла для каждого значения в массиве***

In [ ]:
import numpy as np

arr = np.array([0.3, 0.2, 0.5])

x = np.arcsinh(arr)
y = np.arccosh(np.array([1, 1, 1]))
z = np.arctanh(arr)

x,y,z

(array([0.29567305, 0.19869011, 0.48121183]),
 array([0., 0., 0.]),
 array([0.3095196 , 0.20273255, 0.54930614]))

# ***ЗАДАНИЕ ПО РАЗДЕЛУ NumPy***

1.   Будет текстовый файл с числами которые нужно использовать для создания массива.  

2.   Будет СЛАУ которую нужно решить методом Гаусса/Крамера. 

3.   Решить линейное тензорное уравнение

4.   Решить задачу поиска наименьших квадратов для линейного матричного уравнения.

5.   Будет CSV файл с набором измерений. Нужно рассчитать дисперсию, среднеквадратичное отклонение, отобразить гистограмму и решить задачу поиска наименьших квадратов.


Нужно реализовать программу, которая принимает текстовый файл (в файле есть все данные для заданий 1-4) и записывает ответы для каждого задания в единый файл и сохраняет его на компьютере.

Для задания 5 все то же самое только принимает CSV и возвращает .txt файл + изображение с гистограммой + изображение с решением задачи поиска наименьших квадратов.








#***КОНТРОЛЬНЫЕ ВОПРОСЫ***

1.   Какие типы данных поддерживает NumPy?
2.   Что такое машинное обучение? Где находит применение?
3.   Что такое наука о данных? Где находит применение?
4.   Нужны ли физику, на Ваш взгляд, навыки в области машинного обучения и науки о данных? Почему?



# Pandas

[Ссылка на интерактивный учебник](https://colab.research.google.com/drive/1dHCXHce6TerFQNnnL6U1NxvBUbnEpscP#scrollTo=I0nAGPZ0EGu1)

[Презентация](https://docs.google.com/presentation/d/1k3ZtgcxQE8nkELOy2UJJdjHiMvcr301aWmLWqeAvqeQ/edit#slide=id.g1bc00e5c921_2_661)

[Документация](https://pandas.pydata.org/)


# Matplotlib


[Ссылка на интерактивный учебник](https://colab.research.google.com/drive/1pNRfVksVBfXwje2jSPgkkqJEcilaYHXD#scrollTo=lBSOR2jXOJ88)

[Презентация](https://docs.google.com/presentation/d/1HnMsELAZ5AQsPIewYWgvVBFYOzJ2lbkFsZNRsLTsPwk/edit#slide=id.p)

[Официальная документация](https://matplotlib.org/)

#Seaborn


[Ссылка на интерактивный учебник](https://colab.research.google.com/drive/1F6bZK7MyzvZheZEWPcCNib9Iv2sij4Rw)

[Презентация](https://docs.google.com/presentation/d/1uUEZ8r6bx3KtTJ4LV8XxBWwoFec8MljjCfA7UqX_T1M/edit#slide=id.g181bfb9cb2c_0_83)

[Документация](https://seaborn.pydata.org/)



# ***Полезные источники для выполнения лабораторных работ и подготовки к экзамену***

1.   Data Science. Наука о данных с нуля (Джоэл Грас)

2.   Прикладное машинное обучение с помощью scikit-learn и tensorflow 

3.   Python для сложных задач (Дж. Вандер Плас)

4.   Линейная алгебра на Python (Devpractise team)

2.   Data driven science and engineering. Machine learning, dynamical systems and control (Steven L. Brunton, J. Nathan Kutz)

  # **[Ссылка на электронные версии книг](https://drive.google.com/drive/folders/1mpl_J1kqxaVPoewaNZnwbyifBKJWY1p8?usp=sharing)**



